// GENERATED by tools/gen_korean_assets.py from assets/korean/content.json.
// 自动生成，请勿手改：改 content.json 后重新运行生成器。
#pragma once

#define KO_LETTER_COUNT 40
#define KO_LETTER_GROUP_COUNT 4
#define KO_WORD_COUNT 167
#define KO_TOPIC_COUNT 13
#define KO_PHRASE_COUNT 28
#define KO_PHRASE_GROUP_COUNT 5
#define KO_CLIP_COUNT 256
