#!/usr/bin/env python3
"""从 assets/korean/content.json 生成韩语学习应用的全部派生源码。

生成物（都已提交，构建固件时不需要任何额外工具）：

  main/ko_strings.h           界面文字（中文 / 韩文）宏，应用代码只引用这些宏
  main/ko_content_gen.h       条目数量与发音片段数量
  main/ko_content_gen.c       字母 / 词汇 / 短语数据表（const，驻留 Flash）
  assets/fonts/ko_*.c         按字符集裁剪的 LVGL 字体（lv_font_conv 生成）
  assets/fonts/ko_fonts.manifest.json   字体来源、命令、字符清单与摘要

用法：
  python3 tools/gen_korean_assets.py generate            # 只重新生成 C 数据与字符串
  python3 tools/gen_korean_assets.py generate --fonts \\
      --lv-font-conv <path> --font-sc <SourceHanSansSC-Regular.otf> \\
      --font-kr <SourceHanSansKR-Regular.otf>            # 同时重新生成字体
  python3 tools/gen_korean_assets.py check               # 静态门禁：检查生成物没有过期

`check` 不需要 Node、lv_font_conv 或源字体：它重新推导期望内容，并把已提交的字体
.c 文件里的 cmap 解析回码点，与 manifest 和当前内容逐一对照。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import korean_content as kc  # noqa: E402

ROOT = kc.ROOT
FONT_DIR = ROOT / "assets" / "fonts"
MANIFEST_PATH = FONT_DIR / "ko_fonts.manifest.json"
STRINGS_H = ROOT / "main" / "ko_strings.h"
CONTENT_H = ROOT / "main" / "ko_content_gen.h"
CONTENT_C = ROOT / "main" / "ko_content_gen.c"

CONVERTER_VERSION = "1.5.3"
# name -> (size px, bpp)。大号字体用 2bpp：抗锯齿够用，Flash 只占一半。
FONT_SPECS = {
    "ko_zh14": (14, 4),
    "ko_zh20": (20, 4),
    "ko_ko24": (24, 4),
    "ko_ko32": (32, 4),
    "ko_ko48": (48, 2),
    "ko_jamo96": (96, 2),
}
SOURCE_FONTS = {
    "sc": {
        "file": "SourceHanSansSC-Regular.otf",
        "license": "SIL Open Font License 1.1",
        "origin": "https://github.com/adobe-fonts/source-han-sans (SubsetOTF/SC)",
    },
    "kr": {
        "file": "SourceHanSansKR-Regular.otf",
        "license": "SIL Open Font License 1.1",
        "origin": "https://github.com/adobe-fonts/source-han-sans (SubsetOTF/KR)",
    },
}
BANNER = (
    "// GENERATED by tools/gen_korean_assets.py from assets/korean/content.json.\n"
    "// 自动生成，请勿手改：改 content.json 后重新运行生成器。\n"
)


def c_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


# --------------------------------------------------------------------------
# 文本类生成物
# --------------------------------------------------------------------------

def render_strings_header(content: kc.Content) -> str:
    lines = [
        BANNER.rstrip("\n"),
        "// 应用代码不允许直接写中文 / 韩文字面量：全部从这里引用，",
        "// 这样字体字符集才能由同一份内容精确推导（tests/test_korean_assets.py 会检查）。",
        "#pragma once",
        "",
        "// 中文界面文字（用 ko_zh14 / ko_zh20 显示）。",
    ]
    for key, value in content.ui.items():
        lines.append(f"#define KO_S_{key.upper()} {c_string(value)}")
    lines += ["", "// 韩文装饰字（用 ko_ko24 及以上显示）。"]
    for key, value in content.ui_ko.items():
        lines.append(f"#define KO_K_{key.upper()} {c_string(value)}")
    return "\n".join(lines) + "\n"


def render_content_header(content: kc.Content) -> str:
    texts = kc.clip_table(content)
    return (
        BANNER
        + "#pragma once\n\n"
        + f"#define KO_LETTER_COUNT {len(content.letters)}\n"
        + f"#define KO_LETTER_GROUP_COUNT {len(content.letter_groups)}\n"
        + f"#define KO_WORD_COUNT {len(content.words)}\n"
        + f"#define KO_TOPIC_COUNT {len(content.topics)}\n"
        + f"#define KO_PHRASE_COUNT {len(content.phrases)}\n"
        + f"#define KO_PHRASE_GROUP_COUNT {len(content.phrase_groups)}\n"
        + f"#define KO_CLIP_COUNT {len(texts)}\n"
    )


def render_content_source(content: kc.Content) -> str:
    texts = kc.clip_table(content)
    out = [BANNER.rstrip("\n"), '#include "ko_content.h"', ""]

    out.append("const ko_letter_group_t ko_letter_groups[KO_LETTER_GROUP_COUNT] = {")
    first = 0
    for group in content.letter_groups:
        count = sum(1 for l in content.letters if l["group"] == group["id"])
        out.append(
            f"    {{ .zh = {c_string(group['zh'])}, .ko = {c_string(group['ko'])}, "
            f".first = {first}, .count = {count} }},"
        )
        first += count
    out += ["};", ""]

    out.append("const ko_letter_t ko_letters[KO_LETTER_COUNT] = {")
    for letter in content.letters:
        out.append(
            "    { "
            f".ch = {c_string(letter['ch'])}, .name = {c_string(letter['name'])}, "
            f".name_rom = {c_string(letter['name_rom'])}, .sound = {c_string(letter['sound'])}, "
            f".hint = {c_string(letter['hint'])}, .pair = {c_string(letter['pair'])}, "
            f".syl = {c_string(letter['syl'])}, .syl_rom = {c_string(letter['syl_rom'])}, "
            f".ex = {c_string(letter['ex'])}, .ex_rom = {c_string(letter['ex_rom'])}, "
            f".ex_zh = {c_string(letter['ex_zh'])}, "
            f".name_clip = {kc.clip_id(texts, letter['name'])}, "
            f".ex_clip = {kc.clip_id(texts, letter['ex'])} }},"
        )
    out += ["};", ""]

    def item_rows(items: list) -> list[str]:
        return [
            f"    {{ .ko = {c_string(i['ko'])}, .rom = {c_string(i['rom'])}, "
            f".zh = {c_string(i['zh'])}, .clip = {kc.clip_id(texts, i['ko'])} }},"
            for i in items
        ]

    def deck_rows(decks: list, key: str) -> list[str]:
        rows, start = [], 0
        for deck in decks:
            rows.append(
                f"    {{ .zh = {c_string(deck['zh'])}, .first = {start}, .count = {len(deck[key])} }},"
            )
            start += len(deck[key])
        return rows

    out.append("const ko_item_t ko_words[KO_WORD_COUNT] = {")
    out += item_rows(content.words)
    out += ["};", "", "const ko_deck_t ko_topics[KO_TOPIC_COUNT] = {"]
    out += deck_rows(content.topics, "words")
    out += ["};", "", "const ko_item_t ko_phrases[KO_PHRASE_COUNT] = {"]
    out += item_rows(content.phrases)
    out += ["};", "", "const ko_deck_t ko_phrase_groups[KO_PHRASE_GROUP_COUNT] = {"]
    out += deck_rows(content.phrase_groups, "phrases")
    out += ["};", ""]
    return "\n".join(out)


def expected_text_outputs(content: kc.Content) -> dict[Path, str]:
    return {
        STRINGS_H: render_strings_header(content),
        CONTENT_H: render_content_header(content),
        CONTENT_C: render_content_source(content),
    }


# --------------------------------------------------------------------------
# 字体
# --------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def parse_font_codepoints(path: Path) -> set[int]:
    """把 lv_font_conv 生成的 .c 里的 cmap 解析回码点集合。

    只支持 lv_font_conv 对"若干离散字形"实际会产出的几种 cmap 形式；遇到不认识的
    形式直接报错，而不是悄悄漏算——覆盖检查宁可失败也不能给出假的 PASS。
    """
    text = path.read_text(encoding="utf-8")
    unicode_lists = {
        name: [int(v, 0) for v in re.findall(r"0x[0-9A-Fa-f]+|\d+", body)]
        for name, body in re.findall(
            r"static const uint16_t (unicode_list_\d+)\[\]\s*=\s*\{(.*?)\};", text, flags=re.S
        )
    }
    cmaps_body = re.search(
        r"static const lv_font_fmt_txt_cmap_t cmaps\[\]\s*=\s*\{(.*?)\n\};", text, flags=re.S
    )
    if not cmaps_body:
        raise ValueError(f"{path.name}: cannot find cmaps[]")
    points: set[int] = set()
    for entry in re.findall(r"\{(.*?)\}", cmaps_body.group(1), flags=re.S):
        fields = dict(re.findall(r"\.(\w+)\s*=\s*([\w\.]+)", entry))
        if not fields:
            continue
        start = int(fields["range_start"], 0)
        length = int(fields["range_length"], 0)
        kind = fields["type"]
        if kind in ("LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY", "LV_FONT_FMT_TXT_CMAP_FORMAT0_FULL"):
            points.update(range(start, start + length))
        elif kind == "LV_FONT_FMT_TXT_CMAP_SPARSE_TINY":
            offsets = unicode_lists[fields["unicode_list"]]
            points.update(start + off for off in offsets)
        else:
            raise ValueError(f"{path.name}: unsupported cmap type {kind}")
    # glyph_id 0 是占位字形，cmap 不含它，无需剔除。
    return points


def manifest_expected(content: kc.Content) -> dict:
    fonts = {}
    for name, (size, bpp) in FONT_SPECS.items():
        points = kc.charset(content, name)
        fonts[name] = {
            "size": size,
            "bpp": bpp,
            "file": f"{name}.c",
            "charset_sha256": kc.charset_digest(points),
            "sc_ranges": kc.to_ranges(points["sc"]),
            "kr_ranges": kc.to_ranges(points["kr"]),
            "glyph_count": len(points["sc"]) + len(points["kr"]),
        }
    return fonts


def run_lv_font_conv(converter: str, sources: dict[str, Path], name: str,
                     points: dict[str, list[int]], size: int, bpp: int, out: Path) -> list[str]:
    cmd = [converter]
    for key in ("sc", "kr"):
        if points[key]:
            cmd += ["--font", str(sources[key]), "--range", kc.to_ranges(points[key])]
    cmd += [
        "--size", str(size), "--bpp", str(bpp), "--format", "lvgl",
        "--lv-font-name", name, "--lv-include", "lvgl.h",
        "--no-compress", "--no-kerning", "--output", str(out),
    ]
    subprocess.run(cmd, check=True)
    # lv_font_conv 把完整命令行（含源字体和输出的绝对路径，也就带出了本机用户名）写进文件头注释。
    # 换成文件名 / 仓库相对路径：生成物可复现，也不泄露开发机路径。
    text = out.read_text(encoding="utf-8")
    for source in sources.values():
        text = text.replace(str(source), source.name)
    text = text.replace(str(out), f"assets/fonts/{out.name}")
    out.write_text(text, encoding="utf-8")
    return cmd


def check_sources_have_glyphs(content: kc.Content, sources: dict[str, Path]) -> None:
    """请求的码点必须真的存在于源字体里：lv_font_conv 对缺失码点是静默跳过的。"""
    try:
        from fontTools.ttLib import TTFont
    except ImportError:  # 开发工具：没有 fontTools 就明确说明并跳过这一步
        print("WARNING: fontTools not installed; skipping source glyph presence check",
              file=sys.stderr)
        return
    cmaps = {key: TTFont(str(path), lazy=True).getBestCmap() for key, path in sources.items()}
    missing = []
    for name in FONT_SPECS:
        for key, points in kc.charset(content, name).items():
            missing += [(name, key, cp) for cp in points if cp not in cmaps[key]]
    if missing:
        detail = ", ".join(f"{n}:{k}:U+{cp:04X}" for n, k, cp in missing[:20])
        raise SystemExit(f"ERROR: source font lacks requested glyphs: {detail}")


def generate_fonts(content: kc.Content, converter: str, sources: dict[str, Path]) -> None:
    check_sources_have_glyphs(content, sources)
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {
        "converter": {"name": "lv_font_conv", "version": CONVERTER_VERSION},
        "lvgl": "9.5.0",
        "sources": {
            key: {**meta, "sha256": sha256_file(sources[key]), "bytes": sources[key].stat().st_size}
            for key, meta in SOURCE_FONTS.items()
        },
        "fonts": {},
    }
    expected = manifest_expected(content)
    for name, (size, bpp) in FONT_SPECS.items():
        out = FONT_DIR / f"{name}.c"
        cmd = run_lv_font_conv(converter, sources, name, kc.charset(content, name), size, bpp, out)
        # 记录命令时把机器相关的绝对路径换成源字体文件名，manifest 才可复现、可提交。
        shown = [Path(part).name if part in map(str, sources.values()) else part
                 for part in cmd]
        shown[0] = "lv_font_conv"
        shown = [f"assets/fonts/{name}.c" if part == str(out) else part for part in shown]
        manifest["fonts"][name] = {
            **expected[name],
            "output_bytes": out.stat().st_size,
            "output_sha256": sha256_file(out),
            "command": shown,
        }
        print(f"generated {out.relative_to(ROOT)} ({out.stat().st_size} bytes)")
    MANIFEST_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                             encoding="utf-8")
    print(f"wrote {MANIFEST_PATH.relative_to(ROOT)}")


# --------------------------------------------------------------------------
# check：门禁用，全部只读
# --------------------------------------------------------------------------

def run_check(content: kc.Content) -> list[str]:
    errors: list[str] = []
    for path, text in expected_text_outputs(content).items():
        if not path.is_file():
            errors.append(f"{path.relative_to(ROOT)}: missing (run generate)")
        elif path.read_text(encoding="utf-8") != text:
            errors.append(f"{path.relative_to(ROOT)}: stale, regenerate from content.json")

    if not MANIFEST_PATH.is_file():
        errors.append(f"{MANIFEST_PATH.relative_to(ROOT)}: missing (run generate --fonts)")
        return errors
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    expected = manifest_expected(content)
    for name in FONT_SPECS:
        recorded = manifest.get("fonts", {}).get(name)
        if not recorded:
            errors.append(f"manifest: no entry for {name}")
            continue
        for key in ("size", "bpp", "charset_sha256", "sc_ranges", "kr_ranges", "glyph_count"):
            if recorded.get(key) != expected[name][key]:
                errors.append(f"{name}: manifest {key} is stale (content changed; regenerate fonts)")
        font_path = FONT_DIR / f"{name}.c"
        if not font_path.is_file():
            errors.append(f"{font_path.relative_to(ROOT)}: missing")
            continue
        if sha256_file(font_path) != recorded.get("output_sha256"):
            errors.append(f"{name}: .c file does not match manifest output_sha256")
            continue
        try:
            actual = parse_font_codepoints(font_path)
        except ValueError as error:
            errors.append(str(error))
            continue
        wanted = set(kc.charset(content, name)["sc"]) | set(kc.charset(content, name)["kr"])
        if actual != wanted:
            lost = sorted(wanted - actual)[:10]
            extra = sorted(actual - wanted)[:10]
            errors.append(
                f"{name}: cmap differs from required charset "
                f"(missing {[f'U+{c:04X}' for c in lost]}, extra {[f'U+{c:04X}' for c in extra]})"
            )
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("generate", help="regenerate derived sources")
    gen.add_argument("--fonts", action="store_true", help="also regenerate the LVGL fonts")
    gen.add_argument("--lv-font-conv", default=os.environ.get("LV_FONT_CONV", "lv_font_conv"))
    gen.add_argument("--font-sc", default=os.environ.get("KO_FONT_SC"))
    gen.add_argument("--font-kr", default=os.environ.get("KO_FONT_KR"))
    sub.add_parser("check", help="verify committed outputs are current")
    args = parser.parse_args(argv)

    content = kc.load()
    if args.command == "check":
        errors = run_check(content)
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        if errors:
            return 1
        print("Korean assets: PASS (generated sources and fonts match content.json)")
        return 0

    for path, text in expected_text_outputs(content).items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    if args.fonts:
        if not args.font_sc or not args.font_kr:
            parser.error("--fonts needs --font-sc and --font-kr (or KO_FONT_SC / KO_FONT_KR)")
        sources = {"sc": Path(args.font_sc), "kr": Path(args.font_kr)}
        for key, path in sources.items():
            if not path.is_file():
                parser.error(f"source font not found: {path}")
            if path.name != SOURCE_FONTS[key]["file"]:
                parser.error(f"--font-{key} must be {SOURCE_FONTS[key]['file']}")
        generate_fonts(content, args.lv_font_conv, sources)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
